spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: focusbuddy
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org:
      springframework:
        security: DEBUG
token:
  signin:
    key: ${JWT_SECRET_KEY}

security:
  jwt:
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION}
