name: FocusBuddy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Lint & Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Verify Maven Wrapper
        run: |
          cd backend
          mvn -N io.takari:maven:wrapper

      - name: Install Dependencies
        run: |
          cd backend
          ./mvnw clean install -DskipTests

      - name: Checkstyle Code Linting
        run: |
          cd backend
          ./mvnw checkstyle:check

      - name: Run Tests
        run: |
          cd backend
          ./mvnw test
